In [48]:
import pandas as pd
import numpy as np

import matplotlib as mpl
import matplotlib.pyplot as plt

In [7]:
file = '../DATA/y_conDF.csv'

In [13]:
y_conDF = pd.read_csv(file)
y_conDF.head(10)

,age,gender,membership_type_1,membership_type_2,membership_type_3,membership_type_4,membership_type_5,membership_type_6,tran_date,tran_time,...,ticket_cancel,discount_type,performance_code,pre_open_date,open_date,genre,place,running_time,intermission,member_yn
0,50.0,F,골드,무료,그린,NaN,NaN,NaN,20220114,1512,...,2,일반,302,20220114.0,20220115.0,교향곡,콘서트홀,120,15,Y
1,50.0,M,무료,NaN,NaN,NaN,NaN,NaN,20220206,1615,...,0,일반,897,20220109.0,20220110.0,독주,콘서트홀,90,0,Y
2,30.0,F,블루,무료,NaN,NaN,NaN,NaN,20181124,1145,...,2,블루회원 할인20%,528,20181119.0,20181119.0,교향곡,콘서트홀,100,15,Y
3,50.0,F,무료,NaN,NaN,NaN,NaN,NaN,20191005,1417,...,0,K-lang 멤버십 회원(1인2매)20%,315,NaN,20191005.0,오페라,콘서트홀,120,15,Y
4,50.0,M,골드,무료,NaN,NaN,NaN,NaN,20221030,1645,...,2,일반,2631,20221105.0,20221030.0,교향곡,콘서트홀,120,20,Y
5,30.0,F,무료,그린,NaN,NaN,NaN,NaN,20230224,2214,...,0,일반,1684,20230218.0,20230219.0,합창,콘서트홀,100,15,Y
6,70.0,M,골드,무료,NaN,NaN,NaN,NaN,20191220,1106,...,0,골드회원 할인30%,76,20191220.0,20191223.0,클래식,콘서트홀,120,15,Y
7,20.0,F,무료,싹틔우미,NaN,NaN,NaN,NaN,20230327,1601,...,0,싹틔우미 할인40%,221,20230225.0,20230226.0,클래식,콘서트홀,150,15,Y
8,50.0,F,블루,무료,NaN,NaN,NaN,NaN,20230317,1348,...,0,라흐마니노프탄생150주년(8매/3.27까지)20%,221,20230225.0,20230226.0,클래식,콘서트홀,150,15,Y
9,50.0,M,골드,무료,NaN,NaN,NaN,NaN,20230514,1606,...,2,일반,2835,20230505.0,20230507.0,교향곡,콘서트홀,120,15,Y

In [61]:
# y_conDF의 장소 데이터는 콘서트홀 뿐이다.
y_conDF['place'].nunique()

1

In [11]:
y_conDF.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 484517 entries, 0 to 484516
Data columns (total 24 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   age                484517 non-null  float64
 1   gender             484517 non-null  object
 2   membership_type_1  484517 non-null  object
 3   membership_type_2  389420 non-null  object
 4   membership_type_3  140416 non-null  object
 5   membership_type_4  25158 non-null   object
 6   membership_type_5  1110 non-null    object
 7   membership_type_6  0 non-null       float64
 8   tran_date          484517 non-null  int64
 9   tran_time          484517 non-null  int64
 10  play_date          484517 non-null  int64
 11  play_st_time       484517 non-null  int64
 12  seat               484517 non-null  object
 13  price              484517 non-null  int64
 14  ticket_cancel      484517 non-null  int64
 15  discount_type      484517 non-null  object
 16  performance_code   484517 non-null  int64
 17  pre_open_date      342050 non-null  float64
 18  open_date          484517 non-null  float64
 19  genre              473767 non-null  object
 20  place              484517 non-null  object
 21  running_time       484517 non-null  int64
 22  intermission       484517 non-null  int64
 23  member_yn          484517 non-null  object
dtypes: float64(4), int64(9), object(11)
memory usage: 88.7+ MB

In [12]:
y_conDF.isna().sum()

age                       0
gender                    0
membership_type_1         0
membership_type_2     95097
membership_type_3    344101
membership_type_4    459359
membership_type_5    483407
membership_type_6    484517
tran_date                 0
tran_time                 0
play_date                 0
play_st_time              0
seat                      0
price                     0
ticket_cancel             0
discount_type             0
performance_code          0
pre_open_date        142467
open_date                 0
genre                 10750
place                     0
running_time              0
intermission              0
member_yn                 0
dtype: int64

In [14]:
y_conDF['genre'].unique()

array(['교향곡', '독주', '오페라', '합창', '클래식', '실내악', '성악', '콘서트', nan, '복합장르',
       '재즈', '기타', '크로스오버', '가족극'], dtype=object)

In [15]:
# 장르 목록 구성
con_genre = list(dict.fromkeys(y_conDF['genre'].unique()))  # for문 작성하거나 set함수 적용하여 중복제거. set함수는 원소 나열 순서를 임의로 바꾼다.
con_genre = [item for item in con_genre if str(item) != 'nan']
con_genre

['교향곡',
 '독주',
 '오페라',
 '합창',
 '클래식',
 '실내악',
 '성악',
 '콘서트',
 '복합장르',
 '재즈',
 '기타',
 '크로스오버',
 '가족극']

In [17]:
len(y_conDF)

484517

In [16]:
y_conDF.dropna(subset = ['genre'])

,age,gender,membership_type_1,membership_type_2,membership_type_3,membership_type_4,membership_type_5,membership_type_6,tran_date,tran_time,...,ticket_cancel,discount_type,performance_code,pre_open_date,open_date,genre,place,running_time,intermission,member_yn
0,50.0,F,골드,무료,그린,NaN,NaN,NaN,20220114,1512,...,2,일반,302,20220114.0,20220115.0,교향곡,콘서트홀,120,15,Y
1,50.0,M,무료,NaN,NaN,NaN,NaN,NaN,20220206,1615,...,0,일반,897,20220109.0,20220110.0,독주,콘서트홀,90,0,Y
2,30.0,F,블루,무료,NaN,NaN,NaN,NaN,20181124,1145,...,2,블루회원 할인20%,528,20181119.0,20181119.0,교향곡,콘서트홀,100,15,Y
3,50.0,F,무료,NaN,NaN,NaN,NaN,NaN,20191005,1417,...,0,K-lang 멤버십 회원(1인2매)20%,315,NaN,20191005.0,오페라,콘서트홀,120,15,Y
4,50.0,M,골드,무료,NaN,NaN,NaN,NaN,20221030,1645,...,2,일반,2631,20221105.0,20221030.0,교향곡,콘서트홀,120,20,Y
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
484512,60.0,F,골드,무료,NaN,NaN,NaN,NaN,20181223,1227,...,0,일반,282,NaN,20181202.0,교향곡,콘서트홀,120,15,Y
484513,30.0,F,무료,NaN,NaN,NaN,NaN,NaN,20230516,1743,...,0,일반,1666,20230317.0,20230318.0,실내악,콘서트홀,85,15,Y
484514,60.0,F,무료,그린,NaN,NaN,NaN,NaN,20210618,1509,...,2,일반,887,20210618.0,20210620.0,교향곡,콘서트홀,110,20,Y
484515,50.0,M,무료,NaN,NaN,NaN,NaN,NaN,20230522,1729,...,0,일반,2825,20230505.0,20230507.0,교향곡,콘서트홀,120,15,Y
484516,20.0,F,무료,싹틔우미,NaN,NaN,NaN,NaN,20221224,1223,...,0,청소년(만7세~만24세/본인만)30%,313,NaN,20221223.0,교향곡,콘서트홀,120,0,Y

In [71]:
new_tran_time = []
for j in y_conDF['tran_time'].astype(str):
    if len(j) in [1,2,3]:
        new_tran_time.append(j.zfill(4))

new_tran_time = list(map(int, new_tran_time))
y_conDF['tran_time'] = new_tran_time

ValueError: Length of values (90459) does not match length of index (484517)

In [29]:
time_y_conDF = y_conDF.sort_values(by = ['play_date', 'play_st_time', 'tran_date', 'tran_time'])

In [31]:
time_y_conDF.head()

,age,gender,membership_type_1,membership_type_2,membership_type_3,membership_type_4,membership_type_5,membership_type_6,tran_date,tran_time,...,ticket_cancel,discount_type,performance_code,pre_open_date,open_date,genre,place,running_time,intermission,member_yn
90124,50.0,M,무료,NaN,NaN,NaN,NaN,NaN,20181101,1105,...,0,일반,715,20181028.0,20181029.0,클래식,콘서트홀,120,15,Y
159258,50.0,M,무료,NaN,NaN,NaN,NaN,NaN,20181101,1105,...,0,장애인/국가유공자 할인50%,715,20181028.0,20181029.0,클래식,콘서트홀,120,15,Y
196227,40.0,F,무료,NaN,NaN,NaN,NaN,NaN,20181101,2245,...,0,일반,715,20181028.0,20181029.0,클래식,콘서트홀,120,15,Y
360692,40.0,F,무료,NaN,NaN,NaN,NaN,NaN,20181101,2245,...,0,일반,715,20181028.0,20181029.0,클래식,콘서트홀,120,15,Y
439891,70.0,F,골드,무료,NaN,NaN,NaN,NaN,20181102,1446,...,0,골드회원 할인30%,715,20181028.0,20181029.0,클래식,콘서트홀,120,15,Y

In [67]:
# 시간별로 정렬하여 csv파일로 변환
time_y_conDF.to_csv('time_y_conDF.csv', index = False)

In [54]:
time_y_conDF['play_date'].nunique()

679

In [55]:
time_y_conDF['play_st_time'].nunique()

9

In [60]:
time_y_conDF[time_y_conDF['play_date'] == 20220204]['play_st_time'].nunique()

1

In [62]:
time_y_conDF[time_y_conDF['play_date'] == 20200229]['play_st_time'].nunique()

1

In [65]:
len(set(time_y_conDF['play_date']))

679

In [66]:
for date in set(time_y_conDF['play_date']):
    if time_y_conDF[time_y_conDF['play_date'] == date]['play_st_time'].nunique() != 1:
        print('하루에 두 번 공연을 한 적이 있습니다.')

하루에 두 번 공연을 한 적이 있습니다.
하루에 두 번 공연을 한 적이 있습니다.
하루에 두 번 공연을 한 적이 있습니다.
하루에 두 번 공연을 한 적이 있습니다.
하루에 두 번 공연을 한 적이 있습니다.
하루에 두 번 공연을 한 적이 있습니다.
하루에 두 번 공연을 한 적이 있습니다.
하루에 두 번 공연을 한 적이 있습니다.
하루에 두 번 공연을 한 적이 있습니다.
하루에 두 번 공연을 한 적이 있습니다.
하루에 두 번 공연을 한 적이 있습니다.

In [51]:
df = time_y_conDF.copy()
df = df[df['ticket_cancel'] == 0]
df[['genre', 'play_date'].value_counts()  # 장르 결측 샘플 제외

#list(dict.fromkeys(df[['genre', 'plat_date'].value_counts()))

# x = np.arange(len(show_nums))
# plt.figure(figsize = (15, 5))
# plt.bar(x, show_nums)
# plt.xticks(x, con_genre)
# plt.title('장르별 공연 횟수', size = 15)
# plt.ylabel('공연 횟수', size = 15)

[147666, 64084, 30665, 14209, 9247, 6947, 3478, 3413, 2442, 475, 119, 104, 19]

In [45]:
# 회원 데이터에서 각 장르별 공연 횟수

df = time_y_conDF.copy()
df = df[df['ticket_cancel'] == 0]

show_nums = []
for i in con_genre:
    df = sty_df[sty_df['genre'] == i]
    show_nums.append(len(set(list(df['play_date_time']))))

x = np.arange(len(show_nums))
plt.figure(figsize = (15, 5))
plt.bar(x, show_nums)
plt.xticks(x, con_genre)
plt.title('장르별 공연 횟수', size = 15)
plt.ylabel('공연 횟수', size = 15)

for i, v in enumerate(x):
        plt.text(v, show_nums[i], show_nums[i], size = 12, color='blue', horizontalalignment='center', verticalalignment='bottom')   # 좌표 (x1축 = v, y축 = y0[0]..y0[1], 표시 = y0[0]..y0[1])
                  # verticalalignment (top, center, bottom)
plt.show()

90124     False
159258    False
196227    False
360692    False
439891    False
          ...
221925    False
141258    False
414126    False
152811    False
320894    False
Name: genre, Length: 484517, dtype: bool