In [115]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import sys

In [116]:
sys.setrecursionlimit(1000)

In [117]:
print(pd.__version__)

2.0.3

In [118]:
DF = pd.read_csv(
    '../.venv/tickets.csv',
    parse_dates=[
        'tran_date',  
        'play_date', 
        'pre_open_date', 
        'open_date',
        ]
)

In [119]:
DF.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1920868 entries, 0 to 1920867
Data columns (total 24 columns):
 #   Column             Dtype
---  ------             -----
 0   age                float64
 1   gender             object
 2   membership_type_1  object
 3   membership_type_2  object
 4   membership_type_3  object
 5   membership_type_4  object
 6   membership_type_5  object
 7   membership_type_6  float64
 8   tran_date          datetime64[ns]
 9   tran_time          int64
 10  play_date          datetime64[ns]
 11  play_st_time       int64
 12  seat               object
 13  price              int64
 14  ticket_cancel      int64
 15  discount_type      object
 16  performance_code   int64
 17  pre_open_date      datetime64[ns]
 18  open_date          datetime64[ns]
 19  genre              object
 20  place              object
 21  running_time       int64
 22  intermission       int64
 23  member_yn          object
dtypes: datetime64[ns](4), float64(2), int64(7), object(11)
memory usage: 351.7+ MB

In [120]:
DF[DF['tran_time'] == 0]

,age,gender,membership_type_1,membership_type_2,membership_type_3,membership_type_4,membership_type_5,membership_type_6,tran_date,tran_time,...,ticket_cancel,discount_type,performance_code,pre_open_date,open_date,genre,place,running_time,intermission,member_yn
2947,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2023-06-13,0,...,0,일반,2819,2023-04-28,2023-04-29,NaN,콘서트홀,120,15,N
4702,20.0,F,무료,싹틔우미,NaN,NaN,NaN,NaN,2021-12-14,0,...,2,일반,132,2021-11-12,2021-11-12,실내악,IBK챔버홀,90,15,Y
5402,50.0,M,무료,NaN,NaN,NaN,NaN,NaN,2019-01-08,0,...,0,일반,69,2018-11-23,2018-11-24,클래식,IBK챔버홀,100,15,Y
7654,60.0,F,블루,골드,무료,NaN,NaN,NaN,2022-12-14,0,...,0,경로우대(동반1인/만65세이상)50%,450,2022-11-27,2022-11-28,교향곡,콘서트홀,98,15,Y
10651,30.0,M,무료,NaN,NaN,NaN,NaN,NaN,2023-04-14,0,...,0,문화릴레이(1인2매/실물티켓제시)30%,497,NaT,2022-12-25,교향곡,콘서트홀,110,0,Y
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1906230,30.0,M,골드,무료,그린,NaN,NaN,NaN,2023-04-30,0,...,2,장애인/국가유공자 할인50%,1416,2023-02-19,2023-02-20,독주,콘서트홀,135,0,Y
1911781,30.0,M,골드,무료,그린,NaN,NaN,NaN,2023-03-02,0,...,2,의상자(3급이하/본인만)50%,2085,2023-01-07,2023-01-08,교향곡,콘서트홀,120,0,Y
1912793,20.0,F,무료,싹틔우미,NaN,NaN,NaN,NaN,2022-06-09,0,...,2,일반,1635,2022-04-08,2022-04-09,독주,콘서트홀,100,20,Y
1913817,40.0,F,골드,무료,그린,NaN,NaN,NaN,2022-04-30,0,...,2,그린회원 할인5%,306,NaT,2021-12-20,교향곡,콘서트홀,120,15,Y
1918054,50.0,F,무료,그린,NaN,NaN,NaN,NaN,2023-02-27,0,...,2,그린회원 할인5%,863,2023-02-03,2023-02-04,교향곡,콘서트홀,110,20,Y

In [121]:
DF.columns

Index(['age', 'gender', 'membership_type_1', 'membership_type_2',
       'membership_type_3', 'membership_type_4', 'membership_type_5',
       'membership_type_6', 'tran_date', 'tran_time', 'play_date',
       'play_st_time', 'seat', 'price', 'ticket_cancel', 'discount_type',
       'performance_code', 'pre_open_date', 'open_date', 'genre', 'place',
       'running_time', 'intermission', 'member_yn'],
      dtype='object')

In [122]:
DF.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1920868 entries, 0 to 1920867
Data columns (total 24 columns):
 #   Column             Dtype
---  ------             -----
 0   age                float64
 1   gender             object
 2   membership_type_1  object
 3   membership_type_2  object
 4   membership_type_3  object
 5   membership_type_4  object
 6   membership_type_5  object
 7   membership_type_6  float64
 8   tran_date          datetime64[ns]
 9   tran_time          int64
 10  play_date          datetime64[ns]
 11  play_st_time       int64
 12  seat               object
 13  price              int64
 14  ticket_cancel      int64
 15  discount_type      object
 16  performance_code   int64
 17  pre_open_date      datetime64[ns]
 18  open_date          datetime64[ns]
 19  genre              object
 20  place              object
 21  running_time       int64
 22  intermission       int64
 23  member_yn          object
dtypes: datetime64[ns](4), float64(2), int64(7), object(11)
memory usage: 351.7+ MB

In [123]:
priceDF = DF.drop(columns=['age', 'gender', 'running_time', 'tran_date',
                            'intermission', 'member_yn', 'tran_time', 'genre',
                            'pre_open_date', 'open_date', 'ticket_cancel', 'play_st_time',
                            'membership_type_1', 'membership_type_2', 'membership_type_3',
                            'membership_type_4', 'membership_type_5', 'membership_type_6'])
priceDF.sort_values('play_date', inplace=True)
priceDF.set_index(['play_date', 'performance_code'], inplace=True)
priceDF

                                     seat  price discount_type   place
play_date  performance_code
2018-11-17 1674              1층 B블록 11열 1  20000            일반  IBK챔버홀
           1674              1층 B블록 5열 10  20000            일반  IBK챔버홀
           1674              1층 B블록 3열 10   5000       당일할인티켓_  IBK챔버홀
           1674              1층 B블록 3열 14  20000            일반  IBK챔버홀
           1674              1층 B블록 4열 12      0           초대권  IBK챔버홀
...                                   ...    ...           ...     ...
2023-07-07 710                    2층 3열 1  30000            일반   리사이틀홀
           710                  1층 12열 12      0         기획사판매   리사이틀홀
           710                    1층 7열 5  35000    골드회원 할인30%   리사이틀홀
           914                1층 A블록10열 9  60000    싹딜가(블루)40%    콘서트홀
           914                1층 C블록2열 12  65000         공연예매권    콘서트홀

[1920868 rows x 4 columns]

In [124]:
nozeroDF = priceDF[priceDF['price'] != 0]
nozeroDF

                                     seat  price discount_type   place
play_date  performance_code
2018-11-17 1674              1층 B블록 11열 1  20000            일반  IBK챔버홀
           1674              1층 B블록 5열 10  20000            일반  IBK챔버홀
           1674              1층 B블록 3열 10   5000       당일할인티켓_  IBK챔버홀
           1674              1층 B블록 3열 14  20000            일반  IBK챔버홀
           1674              1층 B블록 3열 15  20000            일반  IBK챔버홀
...                                   ...    ...           ...     ...
2023-07-07 914               합창석 G블록3열 33  47000     그린회원 할인5%    콘서트홀
           710                    2층 3열 1  30000            일반   리사이틀홀
           710                    1층 7열 5  35000    골드회원 할인30%   리사이틀홀
           914                1층 A블록10열 9  60000    싹딜가(블루)40%    콘서트홀
           914                1층 C블록2열 12  65000         공연예매권    콘서트홀

[673496 rows x 4 columns]

In [125]:
noDis = nozeroDF[nozeroDF['discount_type']=='일반']
yesDis = nozeroDF[nozeroDF['discount_type']!='일반']

In [126]:
no_percent = [i for i in yesDis['discount_type'].unique() if '%' not in i]
no_percent, len(no_percent)

(['당일할인티켓_',
  '당일할인티켓',
  '차액',
  '2+1 특별할인',
  '청소년(8세이상~만24세이하)',
  '싹틔우미 할인',
  '공연예매권',
  '특판B',
  '특판D',
  '골드회원+음반 패키지',
  '초/중/고/대학생 할인(본인만)',
  '특별할인(2+1)',
  '3인패키지',
  '4인패키지',
  '골드회원+음반패키지',
  '초/중/고등학생 할인(본인만)',
  '초/중/고/대학생(대학원생) 할인',
  '특판A',
  '초/중/고/대학생 할인(본인)',
  '초/중/고/대학생 할인',
  '초/중/고/대학생(본인)+음반패키지',
  '골드회원 할인+음반패키지',
  '초/중/고/대학생',
  '20,000원 할인',
  '일만원의 나눔',
  '삼만원의 행복',
  '오만원의 사랑',
  '이만원의 기쁨',
  '조기예매할인(1+1/~9.25까지)',
  '100주년 기념 할인(1+1)',
  '기획사',
  '이랍',
  '학생할인',
  '기획사할인',
  '초대권',
  '공연진행석',
  '초/중/고등학생 할인',
  '도서 인증 (현장제시)',
  '일반석',
  '기획사판매',
  '하비에르 국제학교 학부모, 직원',
  '하비에르 국제학교 재학생',
  'S석 기획사 할인',
  'R석 기획사 할인',
  '수험생 할인(동반1인)',
  'R석 기획사할인',
  'S석 기획사할인',
  '블랙프라이데이 이벤트',
  '도서 인증 A',
  '도서 인증 S',
  '노르웨이의 숲 도서 인증 할인',
  'S석+호두까기인형 패키지',
  'A석+호두까기인형 패키지',
  '초/중/고/대학(원)생 할인'],
 54)

In [127]:
yesDis.shape

(436542, 4)

In [128]:
type(noDis.price)

pandas.core.series.Series

In [129]:
def divide_conquer(df1, df2):
    if df1.shape[0] > 1:
        df1_half = df1.shape[0]//2
        df1 = divide_conquer(df1.iloc[:df1_half], df1.iloc[df1_half:])
    if df2.shape[0] > 1:
        df2_half = df2.shape[0]//2
        df2 = divide_conquer(df2.iloc[:df2_half], df2.iloc[df2_half:])
        
    if df1.shape[0] == 1:
        tmp1 = calOrigin(df1)
        # print(tmp1, end='\n\n\n')
        df1 = pd.DataFrame(tmp1)
    if df2.shape[0] == 1:
        df2 = pd.DataFrame(calOrigin(df2))

    return pd.concat([df1, df2], join='inner')


def calOrigin(sr):
    disType = sr['discount_type'][0]
    origin = sr.iloc[0]['price']
    if '%' in disType:
        rate = disType[-3:-1]
        if rate[-3:-1].isdecimal():
            origin = float(sr.iloc[0]['price']) * (100.0 / (100.0-float(rate)))
            
        else:
            origin = float(sr.iloc[0]['price']) * (100.0 / (100.0-float(rate[-1])))
    else:
        pass
    print(sr.index, end='\n\n\n')
    # sr
    return pd.concat([sr, pd.Series([origin], index=sr.index.tolist())], axis=1)

In [130]:
pd.DataFrame(['10000'])

       0
0  10000

In [131]:
yesDis['discount_type'][1]

'싹틔우미 할인40%'

In [132]:
yesDis.iloc[100:200]

                                     seat  price          discount_type  \
play_date  performance_code
2018-12-06 2153              1층 B블록 16열 2  24000             싹틔우미 할인40%
           2153              1층 B블록 3열 12  10000  초/중/고/대학생(대학원생) 할인50%
           2153               1층 B블록 3열 8  10000  초/중/고/대학생(대학원생) 할인50%
           2153               2층 B블록 1열 1  14000             골드회원 할인30%
           2153              1층 C블록 17열 1  10000                     차액
...                                   ...    ...                    ...
2018-12-15 2                     1층 9열 18  10000        장애인/국가유공자 할인50%
           2                     1층 8열 18  10000        초/중/고/대학생 할인50%
           2                     1층 9열 18  10000        초/중/고/대학생 할인50%
           513                    1층 4열 9   5000        장애인/국가유공자 할인50%
           2                     1층 7열 15  10000        초/중/고/대학생 할인50%

                              place
play_date  performance_code
2018-12-06 2153              IBK챔버홀
           2153              IBK챔버홀
           2153              IBK챔버홀
           2153              IBK챔버홀
           2153              IBK챔버홀
...                             ...
2018-12-15 2                  리사이틀홀
           2                  리사이틀홀
           2                  리사이틀홀
           513                리사이틀홀
           2                  리사이틀홀

[100 rows x 4 columns]

In [133]:
yesDis.iloc[:100]

                                      seat  price          discount_type  \
play_date  performance_code
2018-11-17 1674               1층 B블록 3열 10   5000                당일할인티켓_
           1674              1층 B블록 10열 10  12000             싹틔우미 할인40%
           1674               1층 B블록 11열 1  16000             그린회원 할인20%
           1674                1층 B블록 3열 7  10000        장애인/국가유공자 할인50%
           1674               1층 B블록 11열 8   5000                당일할인티켓_
...                                    ...    ...                    ...
2018-12-06 2153                1층 B블록 3열 4  10000  초/중/고/대학생(대학원생) 할인50%
           2153                  2층 BOX1 5  14000             골드회원 할인30%
           2153               1층 B블록 4열 13  10000  초/중/고/대학생(대학원생) 할인50%
           2153                1층 B블록 3열 7  10000  초/중/고/대학생(대학원생) 할인50%
           2153               1층 B블록 4열 11  10000  초/중/고/대학생(대학원생) 할인50%

                              place
play_date  performance_code
2018-11-17 1674              IBK챔버홀
           1674              IBK챔버홀
           1674              IBK챔버홀
           1674              IBK챔버홀
           1674              IBK챔버홀
...                             ...
2018-12-06 2153              IBK챔버홀
           2153              IBK챔버홀
           2153              IBK챔버홀
           2153              IBK챔버홀
           2153              IBK챔버홀

[100 rows x 4 columns]

In [136]:
import re
pattern = r"(\d+)%"
text = "장애인/국가유공자 할인50%"
match = re.search(pattern, text)
print(match.group())


tmp = yesDis['discount_type']
tmp = tmp.apply(lambda x: int(re.search(pattern, x).group()[:-1]) if '%' in x else np.nan).copy()
yesDis['discount_Num'] = tmp
yesDis['origin Num'] = yesDis['price'] / (1- yesDis['discount_Num']/ 100)
yesDis

50%

C:\Users\Administrator\AppData\Local\Temp\ipykernel_11224\3993096849.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  yesDis['discount_Num'] = tmp
C:\Users\Administrator\AppData\Local\Temp\ipykernel_11224\3993096849.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  yesDis['origin Num'] = yesDis['price'] / (1- yesDis['discount_Num']/ 100)

                                      seat   price    discount_type   place  \
play_date  performance_code
2018-11-17 1674               1층 B블록 3열 10    5000          당일할인티켓_  IBK챔버홀
           1674              1층 B블록 10열 10   12000       싹틔우미 할인40%  IBK챔버홀
           1674               1층 B블록 11열 1   16000       그린회원 할인20%  IBK챔버홀
           1674                1층 B블록 3열 7   10000  장애인/국가유공자 할인50%  IBK챔버홀
           1674               1층 B블록 11열 8    5000          당일할인티켓_  IBK챔버홀
...                                    ...     ...              ...     ...
2023-07-07 914                1층 C블록10열 13  123000        그린회원 할인5%    콘서트홀
           914                합창석 G블록3열 33   47000        그린회원 할인5%    콘서트홀
           710                     1층 7열 5   35000       골드회원 할인30%   리사이틀홀
           914                 1층 A블록10열 9   60000       싹딜가(블루)40%    콘서트홀
           914                 1층 C블록2열 12   65000            공연예매권    콘서트홀

                             discount_Num     origin Num
play_date  performance_code
2018-11-17 1674                       NaN            NaN
           1674                      40.0   20000.000000
           1674                      20.0   20000.000000
           1674                      50.0   20000.000000
           1674                       NaN            NaN
...                                   ...            ...
2023-07-07 914                        5.0  129473.684211
           914                        5.0   49473.684211
           710                       30.0   50000.000000
           914                       40.0  100000.000000
           914                        NaN            NaN

[436542 rows x 6 columns]

In [ ]:
dis_arr = yesDis['discount_type'].unique()
no_percent = [i for i in dis_arr if '%' not in i]
print(no_percent, len(no_percent), sep='\n\n')

['당일할인티켓_', '당일할인티켓', '차액', '2+1 특별할인', '청소년(8세이상~만24세이하)', '싹틔우미 할인', '공연예매권', '특판B', '특판D', '골드회원+음반 패키지', '초/중/고/대학생 할인(본인만)', '특별할인(2+1)', '3인패키지', '4인패키지', '골드회원+음반패키지', '초/중/고등학생 할인(본인만)', '초/중/고/대학생(대학원생) 할인', '특판A', '초/중/고/대학생 할인(본인)', '초/중/고/대학생 할인', '초/중/고/대학생(본인)+음반패키지', '골드회원 할인+음반패키지', '초/중/고/대학생', '20,000원 할인', '일만원의 나눔', '삼만원의 행복', '오만원의 사랑', '이만원의 기쁨', '조기예매할인(1+1/~9.25까지)', '100주년 기념 할인(1+1)', '기획사', '이랍', '학생할인', '기획사할인', '초대권', '공연진행석', '초/중/고등학생 할인', '도서 인증 (현장제시)', '일반석', '기획사판매', '하비에르 국제학교 학부모, 직원', '하비에르 국제학교 재학생', 'S석 기획사 할인', 'R석 기획사 할인', '수험생 할인(동반1인)', 'R석 기획사할인', 'S석 기획사할인', '블랙프라이데이 이벤트', '도서 인증 A', '도서 인증 S', '노르웨이의 숲 도서 인증 할인', 'S석+호두까기인형 패키지', 'A석+호두까기인형 패키지', '초/중/고/대학(원)생 할인']

54

In [ ]:
newDF = nozeroDF[['seat', 'play_st_time']]